### ISSUE TITLE
clean feature is unable to download

### ISSUE THREAD

**Issue by SamXiaosheng** [jeongjin0/detector-cleanse#1]
Thanks to your amazing work, i want to use this project but the clean feature unable to download, could you share it against.

**Comment by jeongjin0** [comment]
Hi @SamXiaosheng, thanks for reporting the issue with the Clean feature download. 
I've fixed the broken link in the README.md file. You can now access it here: https://drive.google.com/file/d/1Qj_5s84HXdgDWG3KRn-zW7oIRGvrouer/view?usp=sharing
