### ISSUE TITLE
Detector cleanse only for Faster-RCNN

### ISSUE THREAD

**Issue by zBazinga** [jeongjin0/detector-cleanse#3]
According to the author's description in the paper, this method requires adding clean features on detected bounding boxes . However, for ODA , only Faster-RCNN can provide candidate regions, while the YOLO series cannot provide candidate regions, which may cause the method to be ineffective against ODA. What is your opinion on this?

**Comment by jeongjin0** [comment]
Thank you for your interest in our work. 

In our experiments with Faster-RCNN under ODA assumptions, we observed that the increased number of bounding boxes to be examined led to slower detection speeds. However, we found that it was not necessary to inspect all bounding boxes to detect ODA. Although we have not yet experimented with Detector Cleanse on YOLO, it is reasonable to expect that YOLO may experience an even more severe slowdown in detection speed compared to Faster-RCNN. Nevertheless, based on our findings with Faster-RCNN, it seems plausible that detection under ODA assumptions may still be feasible in YOLO, albeit with additional verification required.

We hope this information is helpful. If you have any further questions or suggestions, please feel free to let us know.

**Comment by zBazinga** [comment]
Thank you for your reply! It has inspired me greatly!

The Detector Cleanse method is a technique transferred from the field of image classification, which doesn't require consideration of quantity. Therefore, indeed, the quantity of bounding boxes can impose certain limitations. For YOLO, in particular, the number of bounding boxes will be further expanded, leading to decreased efficiency.

Wishing you smooth progress in your research!
