### ISSUE TITLE
Could you please provide some poisoned data？

### ISSUE THREAD

**Issue by CooFlow** [jeongjin0/detector-cleanse#5]
After I train a faster-rcnn model, I noticed that script needs to enter a picture of the test.

`python main.py --n 100 --m 0.51 --delta 0.25 --image_path 'path/to/image.jpg' --clean_feature_path 'path/to/clean_feature_images' --weight 'path/to/model/weight.pth'
`
```
        if poisoned:
            print()
            print("Image is poisoned")
            print(f"Coordinate : {coordinates}")
        else:
            print()
            print("Image is clean")

```
 can you provide some **poisoning** data? Or give some guidance to build them.

**Comment by jeongjin0** [comment]
Thank you for your interest in our work.

You can code something like this to generate the images for inspection. The generated directory can then be put into the path of --image_path to calculate FRR and FAR. Alternatively, you can put the images in the directory into the path of --image_path to test a single image for poison.

```python
from data.dataset import Dataset, TestDataset
from torch.utils import data as data_
import torchvision.transforms as transforms
import os
from backdoor_utils import backdoor_inject
from utils.config import opt

def generate_poisoning_data(n=10):
    testset = TestDataset(opt)  # or Dataset(opt)
    test_dataloader = data_.DataLoader(testset, batch_size=1, num_workers=2, shuffle=False)
    image_dir = 'test_images'
    os.makedirs(image_dir, exist_ok=True)

    for i, (image, bbox, label, scale) in enumerate(test_dataloader):
        if i >= n:
            break

        image = transforms.ToPILImage()(image.squeeze(0))
        clean_path = os.path.join(image_dir, f'clean_{i+1}.jpg')
        image.save(clean_path)
        print(f"Saved clean image {i+1} to {clean_path}")

        poisoned_image = backdoor_inject(image, bbox, label)
        poisoned_path = os.path.join(image_dir, f'modified_{i+1}.jpg')
        poisoned_image.save(poisoned_path)
        print(f"Saved poisoned image {i+1} to {poisoned_path}")

generate_poisoning_data()
```

In the code, Dataset, Testset, and opt are the PASCAL VOC 2007 datasets from base repository [simple-faster-rcnn-pytorch](https://github.com/chenyuntc/simple-faster-rcnn-pytorch), and backdoor_inject is the backdoor injection function you used to train the backdoor.

Hope this helps. If you have any further questions, please feel free to ask

**Comment by CooFlow** [comment]
Thanks for you detail explanation!
However, I can't access to this code line:
**`from backdoor_utils import backdoor_inject`**

Can you please make this file available, via “drive” or any other way?
