### ISSUE TITLE
Defense performance drop

### ISSUE THREAD

**Issue by Rookie143** [jeongjin0/detector-cleanse#7]
Thank you for your contribution! I would like to know that I found in the process of reproducing the defense performance and the original text gap is very large (Including my own attempts to understand, and reproducte), I do not know if you have encountered a similar situation? Why :)

**Comment by jeongjin0** [comment]
Thank you for bringing up this implementation issue. I would like to address several key points:

1. First, I want to emphasize that this was not an official implementation, but rather our best attempt at reproducing the defense based on the paper's description.

2. For aspects that weren't clearly detailed in the paper, we had to make reasonable assumptions and estimations. We attempted to contact the authors via email regarding unclear points but didn't receive a response.

3. The main challenge we encountered was handling cases where perturbed images failed to generate predictions for perturbed bounding boxes. Specifically:
The paper didn't provide detailed information about perturbation parameters
Large perturbations (around 50%) often resulted in failure to detect bounding boxes
Small perturbations were insufficient to trigger the desired defense mechanism

4. Our implementation approach:
We only calculated entropy for bounding boxes that maintained a certain IoU threshold after perturbation
We avoided using Faster R-CNN's classifier directly as it would essentially replicate STRIP and it's not applicable to 1-stage detectors like YOLO.
  
5. Regarding ODA (Object Detection Attack), we had several questions about handling cases where triggers caused bounding boxes to disappear and the implications for comprehensive detection.

I apologize if our implementation didn't meet expectations. For our research, we ultimately decided to use the standard STRIP method for defense experiments.
I hope this explanation helps clarify our experience with the reproduction challenges.

**Comment by Rookie143** [comment]
> Thank you for bringing up this implementation issue. I would like to address several key points:
> 
> 1. First, I want to emphasize that this was not an official implementation, but rather our best attempt at reproducing the defense based on the paper's description.
> 2. For aspects that weren't clearly detailed in the paper, we had to make reasonable assumptions and estimations. We attempted to contact the authors via email regarding unclear points but didn't receive a response.
> 3. The main challenge we encountered was handling cases where perturbed images failed to generate predictions for perturbed bounding boxes. Specifically:
>    The paper didn't provide detailed information about perturbation parameters
>    Large perturbations (around 50%) often resulted in failure to detect bounding boxes
>    Small perturbations were insufficient to trigger the desired defense mechanism
> 4. Our implementation approach:
>    We only calculated entropy for bounding boxes that maintained a certain IoU threshold after perturbation
>    We avoided using Faster R-CNN's classifier directly as it would essentially replicate STRIP and it's not applicable to 1-stage detectors like YOLO.
> 5. Regarding ODA (Object Detection Attack), we had several questions about handling cases where triggers caused bounding boxes to disappear and the implications for comprehensive detection.
> 
> I apologize if our implementation didn't meet expectations. For our research, we ultimately decided to use the standard STRIP method for defense experiments. I hope this explanation helps clarify our experience with the reproduction challenges.

Thank you for your contribution to the community. There is no need for you to apologize. We need to thank you instead.

I am very pleased with your detailed reply. Actually, I have been trying to reproduce it before, but found it difficult to achieve results. I suspect it may be my own problem, so I am asking you a question. I am glad to have found the same conclusion as the community. And, thank you again for providing some additional insights!
